# Generated by Django 3.0.8 on 2021-03-16 01:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('perpustakaan', '0003_auto_20210316_0849'),
    ]

    operations = [
        migrations.RenameField(
            model_name='buku',
            old_name='kelompok_id',
            new_name='kelompok',
        ),
    ]
