# Generated by Django 3.0.8 on 2021-03-19 02:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('perpustakaan', '0004_auto_20210316_0851'),
    ]

    operations = [
        migrations.AlterField(
            model_name='kelompok',
            name='nama',
            field=models.CharField(max_length=50),
        ),
    ]
