# Generated by Django 3.0.8 on 2021-03-19 02:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('perpustakaan', '0006_auto_20210319_0916'),
    ]

    operations = [
        migrations.RenameField(
            model_name='buku',
            old_name='kelompok',
            new_name='kelompok_id',
        ),
    ]
