# Generated by Django 3.0.8 on 2021-04-23 05:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('perpustakaan', '0008_auto_20210423_0936'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='buku',
            name='cover',
        ),
        migrations.RemoveField(
            model_name='buku',
            name='tanggal',
        ),
    ]
