# Generated by Django 3.0.8 on 2021-12-11 04:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('perpustakaan', '0010_customer'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Customer',
        ),
    ]
