# Generated by Django 3.0.8 on 2022-01-16 02:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('perpustakaan', '0012_customer'),
    ]

    operations = [
        migrations.AddField(
            model_name='buku',
            name='harga',
            field=models.IntegerField(null=True),
        ),
        migrations.CreateModel(
            name='Transaksi',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('jumlah', models.IntegerField(null=True)),
                ('harga', models.IntegerField()),
                ('total_harga', models.IntegerField()),
                ('buku_id', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='perpustakaan.Buku')),
                ('customer_id', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='perpustakaan.Customer')),
            ],
        ),
    ]
