# Generated by Django 3.0.8 on 2022-01-16 02:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('perpustakaan', '0013_auto_20220116_0944'),
    ]

    operations = [
        migrations.AlterField(
            model_name='buku',
            name='harga',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='buku',
            name='jumlah',
            field=models.IntegerField(default=0),
        ),
    ]
